### PR TITLE
chore: remove unused vetur settings

### PR DESCRIPTION
**Pull request by baseballyama**
This repo doesn't need to use vetur, so I removed it.

### CODE REVIEW

**Comment by baseballyama** [comment]
Hum... Why type error comes...

**Comment by JounQin** [comment]
error @sveltejs/kit@1.0.0-next.464: The engine "node" is incompatible with this module. Expected version ">=16.14". Got "16.13.0"
error Found incompatible module.

**Comment by baseballyama** [comment]
But still, I didn't get why suddenly type error comes from `cacheable-request`...?

https://github.com/ota-meshi/eslint-plugin-svelte/runs/8166580394?check_suite_focus=true#step:5:16

```
Error: node_modules/@types/cacheable-request/index.d.ts(26,42): error TS2709: Cannot use namespace 'ResponseLike' as a type.
```

**Comment by JounQin** [comment]
Because we're not using lock files?

**Comment by baseballyama** [comment]
`cacheable-request` is not updated recently. So I think type is not changed compared to other recent PRs even without lock files. This is weird...

**Comment by JounQin** [comment]
I could also be affected by other global types.

**Comment by baseballyama** [comment]
To avoid `cacheable-request` type error, I added `skipLibCheck` option to `tsconfig.json`.
I'm not sure this is the proper way, but now build and lint are succeeded.

**Review by ota-meshi — APPROVED** [review]
LTGM! Thank you!

**Pull request merged**
