### PR TITLE
chore: migrate config.kit.files.hooks

### PR DESCRIPTION
**Pull request by baseballyama**
Update `svelte.config.mjs` according to https://github.com/sveltejs/kit/pull/6586

### CODE REVIEW

**Review by JounQin — APPROVED** [review]
👍

**Review by ota-meshi — APPROVED** [review]
Thank you!

**Comment by baseballyama** [comment]
I didn't get the reason but CI failed...

**Comment by ota-meshi** [comment]
Something seems to go wrong when using `paths.base` and [imported assets](https://kit.svelte.dev/docs/assets#caching-and-inlining) and `adapter-static`. However, I still don't know what the cause is.

Error:

```console
Error: 404 /_app/immutable/assets/logo-06fafbe9.svg does not begin with `base`, which is configured in `paths.base` and can be imported from `$app/paths` (linked from /eslint-plugin-svelte/)
```

HTML generated by the current job:

```html
      <img src="/_app/immutable/assets/logo-06fafbe9.svg" alt="Logo" class="svelte-jet77t">
```

Current published HTML:

```html
      <img src="/eslint-plugin-svelte/_app/immutable/assets/logo-06fafbe9.svg" alt="Logo" class="svelte-jet77t">
```

**Comment by ota-meshi** [comment]
I found the cause. 

https://github.com/sveltejs/kit/blob/616ec7acace562b4517e1dae6c2fab159f055b78/packages/kit/src/exports/vite/build/utils.js#L149-L151


```js
export function assets_base(config) {
	return config.paths.assets + '/' || config.paths.base + '/' || './';
}
```

The first expression will be 100% truthy.

I'll check if it's already been reported.

**Comment by ota-meshi** [comment]
I opened an issue.
https://github.com/sveltejs/kit/issues/6767
I don't know if I can open a PR because I don't know how to test it yet.

**Comment by ota-meshi** [comment]
I opened a PR.
https://github.com/sveltejs/kit/pull/6769

**Pull request merged**
