### PR TITLE
`all` config

### LINKED ISSUE #369: Export an all config
### Description

Export an all config that contains the default options for all of the rules (except for deprecated ones).

```js
module.exports = {
  extends: ['plugin:svelte/all'],
}
```

### PR DESCRIPTION
**Pull request by DetachHead**
fixes #369

### CODE REVIEW

**Review by ota-meshi — CHANGES_REQUESTED** [review]
Please document the caveats as mentioned in the issue. I think we also need to export from index.ts. Also we need to resolve the CI error.

**Comment by DetachHead** [comment]
added the documentation and the export. as for the CI error, i have no idea what's going on. as far as i can tell it's unrelated because locally when i run the tests after reverting my changes the errors still occur

**Comment by ota-meshi** [comment]
Thank you for the PR.  As you said, the remaining CI errors appear unrelated to the changes in the PR.  I will look into the cause later.

**Review by ota-meshi — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
